import numpy as np
import scipy as sp
from numpy.linalg import inv
from numpy import linalg as LA
from scipy.linalg import fractional_matrix_power
from scipy.linalg import block_diag
import copy


class GFMethod:
    """
    Solve the Wilson GF vibrational eigenvalue problem.

    This class performs harmonic vibrational analysis using the Wilson
    GF method. Given a force-constant matrix (F) and a kinetic energy
    matrix (G), the generalized eigenvalue problem

    .. math::

        GF L = L \\Lambda

    is transformed into an ordinary symmetric eigenvalue problem and
    solved to obtain vibrational frequencies and normal coordinates.

    The procedure consists of:

    1. Constructing the symmetric orthogonalizer

       .. math::

           G^{1/2}

    2. Forming the symmetrized force-constant matrix

       .. math::

           F_O = G^{1/2} F G^{1/2}

    3. Diagonalizing the transformed matrix

       .. math::

           F_O L' = L' \\Lambda

    4. Recovering the normal-coordinate transformation matrix

       .. math::

           L = G^{1/2}L'

    5. Converting the eigenvalues into harmonic vibrational frequencies.

    Optional molecular symmetry support allows the transformed force
    matrix to be block diagonalized by irreducible representation,
    preserving symmetry labels and reducing computational cost.

    Parameters
    ----------
    G : ndarray
        Wilson G-matrix describing the kinetic energy metric in the
        chosen coordinate basis.

    F : ndarray
        Harmonic force-constant matrix in the same coordinate basis
        as the G-matrix.

    zmat : Zmat
        Molecular coordinate object.

    ted : TED
        Total Energy Distribution (TED) object used to analyze and
        print vibrational mode compositions.

    options : object
        User-defined options controlling symmetry handling,
        numerical tolerances, and output formatting.

    symtext : object, optional
        Symmetry information generated by the molecular symmetry
        analysis routines. Required when symmetry block
        diagonalization is enabled.

    sym_sort : list, optional
        User-defined symmetry sorting information.

    Attributes
    ----------
    G : ndarray
        Wilson G-matrix.

    F : ndarray
        Harmonic force-constant matrix.

    G_O : ndarray
        Symmetric orthogonalizer, :math:`G^{1/2}`.

    F_O : ndarray
        Symmetrized force matrix.

    eig_v : ndarray
        Eigenvalues of the GF problem.

    freq : ndarray
        Harmonic vibrational frequencies in cm⁻¹.

    L_p : ndarray
        Eigenvectors of the symmetrized force matrix.

    L : ndarray
        Normal-coordinate transformation matrix.

    irrep_labels : list
        Symmetry labels assigned to vibrational modes when
        symmetry analysis is enabled.

    irrep_degen : list
        Degeneracies associated with the vibrational modes.

    HARTREE_WAVENUM : float
        Conversion factor from Hartree atomic units to cm⁻¹.

    Notes
    -----
    Frequencies are obtained from the square roots of the GF
    eigenvalues:

    .. math::

        \\omega_i = \\sqrt{\\lambda_i}

    Imaginary frequencies are reported as negative values by
    converting the imaginary component of the eigenvalue square root.

    The resulting frequencies are converted from atomic units to
    wavenumbers using

    .. math::

        1\\ \\text{Hartree}
        =
        219474.6313708\\ \\text{cm}^{-1}

    After solving the GF problem, a Total Energy Distribution (TED)
    analysis is performed to determine the contribution of each
    internal coordinate to every normal mode.
    """

    def __init__(self, G, F, zmat, ted, options, symtext=None, sym_sort=[]):
        self.G = G
        self.F = F
        self.zmat = zmat
        self.ted = ted
        self.options = options
        self.symtext = symtext
        self.sym_sort = sym_sort
        self.AMU_ELMASS = 5.48579909065 * (10 ** (-4))
        self.HARTREE_WAVENUM = 219474.6313708

    def run(self):
        """
        Solve the GF vibrational eigenvalue problem.

        Constructs the orthogonalized force matrix, performs the
        diagonalization, computes harmonic frequencies, generates the
        normal-coordinate transformation matrix, and performs a Total
        Energy Distribution (TED) analysis.

        Returns
        -------
        None

        Notes
        -----
        If molecular symmetry is enabled, the transformed force matrix is
        block diagonalized by irreducible representation before
        diagonalization. Otherwise, the full matrix is diagonalized
        directly.

        Results are stored in the attributes:

        - ``freq`` : vibrational frequencies
        - ``L`` : normal-coordinate transformation matrix
        - ``L_p`` : orthogonalized eigenvector matrix
        - ``eig_v`` : GF eigenvalues
        """
        # Construct the orthogonalizer
        self.G_O = fractional_matrix_power(self.G, 0.5)

        # Symmetrize F, diagonalize, then backtransform the eigenvectors.
        self.F_O = np.dot(np.dot(self.G_O, self.F), self.G_O)

        if self.options.molsym_symmetry:
            # allows the block diagonalization of the GF matrix so normal modes stay
            # in the assumed ordering for the level A displacements (Within their symmetry blocks)
            self.block_GF()
        else:
            self.eig_v, self.L_p = LA.eigh(self.F_O)

        self.L_p[np.abs(self.L_p) < self.options.tol] = 0
        self.L = np.dot(self.G_O, self.L_p)
        self.L = np.real(self.L)
        L_p = np.real(self.L_p)
        self.L_p = L_p

        self.L[np.abs(self.L) < self.options.tol] = 0
        # Compute the frequencies by the square root of the eigenvalues.
        self.freq = np.sqrt(self.eig_v, dtype=complex)
        # Filter for imaginary modes.
        for i in range(len(self.freq)):
            if np.real(self.freq[i]) > 0.0:
                self.freq[i] = np.real(self.freq[i])
            else:
                self.freq[i] = -np.imag(self.freq[i])

        # This seems to fix the constant warning I get about casting out imaginary values from the complex numbers,
        # however I will need to test it on transition states to see if it captures the imaginary frequencies.
        self.freq = self.freq.astype(float)

        # Convert from Hartrees to wavenumbers.
        self.freq *= self.HARTREE_WAVENUM
        if self.options.molsym_symmetry:
            for i in range(len(self.freq)):
                print(
                    "frequency #"
                    + "{:3d}".format(i + 1)
                    + ": "
                    + "{:10.2f}".format(self.freq[i])
                    + " {}".format(self.irrep_degen[i])
                    + " x {}".format(self.irrep_labels[i])
                )
        else:
            for i in range(len(self.freq)):
                print(
                    "frequency #"
                    + "{:3d}".format(i + 1)
                    + ": "
                    + "{:10.2f}".format(self.freq[i])
                )
        # Compute and then print the TED.
        print("////////////////////////////////////////////")
        print("//{:^40s}//".format("Total Energy Distribution (TED)"))
        print("////////////////////////////////////////////")
        if self.options.molsym_symmetry:
            self.ted.run(self.L, self.freq, self.symtext, rect_print=False)
        else:
            self.ted.run(self.L, self.freq, self.symtext, rect_print=False)

    def block_GF(self):
        """
        Diagonalize the orthogonalized force matrix by symmetry blocks.

        The transformed force matrix is partitioned into blocks
        corresponding to irreducible representations of the molecular
        point group. Each block is diagonalized independently and the
        resulting eigenvectors are assembled into a block-diagonal
        transformation matrix.

        Returns
        -------
        None

        Notes
        -----
        This procedure preserves symmetry labels and mode ordering,
        which is particularly useful for Concordant Modes calculations
        that rely on symmetry-adapted coordinate transformations.
        """
        self.eigvals, self.eigvecs = [], []
        offset_h = 0
        self.block_fo = []
        self.irrep_labels = []
        self.irrep_degen = []
        for hi, h in enumerate(self.symtext.salcblocks):

            # Extract the block from the supermatrix
            fo = self.extract(self.F_O, offset_h, h.shape[0])
            self.block_fo.append(fo)
            eig_v_h, L_p_h = LA.eigh(fo)
            self.eigvals.append(eig_v_h)
            self.eigvecs.append(L_p_h)
            for i in range(len(eig_v_h)):
                self.irrep_labels.append(self.symtext.irreps[hi].symbol)
                self.irrep_degen.append(self.symtext.irreps[hi].d)

            # UPDATE OFFSET
            offset_h += h.shape[0]
        self.block_eigvals = copy.deepcopy(self.eigvals)
        self.eigvals = [item for sublist in self.eigvals for item in sublist]
        self.eig_v = np.asarray(self.eigvals)
        self.block_eigvecs = copy.deepcopy(self.eigvecs)
        self.L_p = block_diag(*self.eigvecs)

    # function to extract bd matrices from supermatrix
    def extract(self, A, offset, size):
        """
        Extract a square submatrix from a larger matrix.

        Parameters
        ----------
        A : ndarray
            Input matrix.

        offset : int
            Starting row and column index.

        size : int
            Dimension of the block to extract.

        Returns
        -------
        ndarray
            Extracted square submatrix.
        """
        return A[offset : offset + size, offset : offset + size]
