from concordantmodes.molden_template import molden_template
import numpy as np
import json
import os
import qcelemental as qcel
import re
import shutil


class MoldenWriter:
    """
    Write vibrational frequencies and normal-mode displacement vectors to
    a Molden-format file.
    
    This class generates a Molden-compatible output file from the results
    of a Concordant Modes calculation. The output contains the equilibrium
    geometry, harmonic vibrational frequencies, and Cartesian displacement
    vectors corresponding to the computed normal modes, allowing the modes
    to be visualized and animated in Molden and other compatible molecular
    visualization programs.

    Parameters
    ----------
    zmat : Zmat
        Molecular coordinate object containing atomic symbols and
        Cartesian coordinates.

    disps : TransfDisp
        Displacement object containing the normal-coordinate
        displacement geometries. The diagonal elements of
        ``p_disp`` are interpreted as positive displacements along
        individual normal modes.

    freq : ndarray
        Harmonic vibrational frequencies in cm⁻¹.

    Attributes
    ----------
    zmat : Zmat
        Molecular coordinate representation.

    disps : TransfDisp
        Normal-mode displacement information.

    freq : ndarray
        Harmonic vibrational frequencies.

    Notes
    -----
    The generated Molden file contains the following sections:
    
    - ``[ATOMS]``: Atomic labels, atomic numbers, and Cartesian coordinates.
    - ``[FREQ]``: Harmonic vibrational frequencies.
    - ``[FR-COORD]``: Reference equilibrium geometry.
    - ``[FR-NORM-COORD]``: Cartesian representations of the normal modes.
    
    The normal-mode vectors are obtained from the geometries generated by
    displacements along individual normal coordinates. For mode ``i`` the
    Cartesian displacement vector is computed as
    
    .. math::
    
        \Delta \mathbf{r}_i =
        \mathbf{r}_i^{(+)} - \mathbf{r}_0
    
    where :math:`\mathbf{r}_0` is the reference geometry and
    :math:`\mathbf{r}_i^{(+)}` is the geometry displaced along normal
    coordinate :math:`Q_i`.
    
    These vectors therefore represent the Cartesian motion associated with
    the vibrational normal modes obtained from the Concordant Modes
    Algorithm. The vectors are multiplied by a constant scale factor prior
    to writing the Molden file to improve visualization of vibrational
    motion.
    """
    def __init__(
        self,
        zmat,
        disps,
        freq,
    ):
        self.zmat = zmat
        self.disps = disps
        self.freq = freq

    def run(self):
        """
        Generate a Molden-format vibrational analysis file.

        Constructs the Molden sections describing the molecular geometry,
        harmonic frequencies, reference coordinates, and normal-mode
        displacement vectors, then writes the assembled output to a file
        named ``MOLDEN``.

        Returns
        -------
        None

        Notes
        -----
        Atomic numbers are obtained using the QCEngine/QCElemental
        periodic table utilities.

        Normal-mode displacement vectors are derived from the positive
        displacement geometries stored in ``disps.p_disp`` and scaled
        for improved visualization in Molden-compatible viewers.

        The generated file can be opened directly in Molden to animate
        vibrational normal modes and inspect harmonic frequencies.
        """
        geometry = ""
        atom_num = np.array([])
        for i in self.zmat.atom_list:
            atom_num = np.append(atom_num, int(qcel.periodictable.to_atomic_number(i)))

        for i in range(len(self.zmat.cartesians_a)):
            geometry += "{:2<}{:>9}{:>5}{:-20.10f}{:-20.10f}{:-20.10f}\n".format(
                self.zmat.atom_list[i],
                str(i + 1),
                str(int(atom_num[i])),
                self.zmat.cartesians_a[i][0],
                self.zmat.cartesians_a[i][1],
                self.zmat.cartesians_a[i][2],
            )

        frequencies = ""
        for i in self.freq:
            frequencies += "{:-20.10f}\n".format(i)

        fr_geom = ""

        for i in range(len(self.zmat.cartesians_a)):
            fr_geom += "{:<5}{:-20.10f}{:-20.10f}{:-20.10f}\n".format(
                self.zmat.atom_list[i],
                self.zmat.cartesians_a[i][0],
                self.zmat.cartesians_a[i][1],
                self.zmat.cartesians_a[i][2],
            )

        normal_modes = ""
        for i in range(len(self.disps.p_disp)):
            normal_modes += "  vibration{:>23}\n".format(str(i + 1))
            disp = self.disps.p_disp[i, i] - self.zmat.cartesians_a
            disp *= 30
            for j in range(len(disp)):
                normal_modes += "{:-20.10f}{:-20.10f}{:-20.10f}\n".format(
                    disp[j][0], disp[j][1], disp[j][2]
                )

        molden_template = """[Molden Format]\n[ATOMS] AU\n{geometry}[Molden Format]\n [FREQ]\n{frequencies} [FR-COORD]\n{fr_geom} [FR-NORM-COORD]\n{normal_modes}"""
        inout = {
            "geometry": geometry,
            "frequencies": frequencies,
            "fr_geom": fr_geom,
            "normal_modes": normal_modes,
        }
        molden_template = molden_template.format(**inout)

        with open("MOLDEN", "w+") as file:
            file.write(molden_template)
        pass
